### ISSUE TITLE
no module named ‘fused’

### ISSUE THREAD

**Issue by Inori-dn** [Lemok00/IDEAS#1]
(https://user-images.githubusercontent.com/75171131/183353330-c1a561ce-13b7-40fc-a4dd-44ca5134e669.png)
(https://user-images.githubusercontent.com/75171131/183353406-525d33b7-9af6-41bf-a748-d9c5ac660d82.png)
pytorch 1.8.0
cuda 10.2

When I run the code, it will report an error "no module named ‘fused’",I tried all kinds of methods, but none of them could be solved。

**Comment by Lemok00** [comment]
please try PyTorch 1.7.1
